return {
    -- "Pocco81/AutoSave.nvim",
    -- config = function()
    --     require("autosave")
    --         .setup({
    --             enabled = true,
    --             execution_message = "AutoSave: saved at " .. vim.fn.strftime("%H:%M:%S"),
    --             events = { "TextChanged", "VimLeavePre" },
    --             conditions = {
    --                 exists = true,
    --                 filename_is_not = {},
    --                 filetype_is_not = {},
    --                 modifiable = true,
    --             },
    --             write_all_buffers = false,
    --             on_off_commands = true,
    --             clean_command_line_interval = 0,
    --             debounce_delay = 250,
    --         })
    --         .run()
    -- end,
}
